services:
  web:
    image: odoo:17.0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
